branch-defaults:
  master:
    environment: postgresql-env-clone
environment-defaults:
  postgresql-env-clone:
    branch: null
    repository: null
global:
  application_name: Project
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Passenger with Ruby
    2.4 running on 64bit Amazon Linux/2.6.0
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
